#!/bin/sh

DISTFEEDS="/etc/opkg/distfeeds.conf"
[ -f "$DISTFEEDS" ] || exit 0

sed -e 's,https://downloads.immortalwrt.org,https://mirrors.pku.edu.cn/immortalwrt,g' \
    -e 's,https://mirrors.vsean.net/openwrt,https://mirrors.pku.edu.cn/immortalwrt,g' \
    -i.bak "$DISTFEEDS"

exit 0
